use std::fs;
use std::error::Error;

pub fn run_part1(input: &str) -> Result<String, Box<dyn Error>> {
    
}
